### ISSUE TITLE
Error: "Unable to mount image" in dmsetup call

### ISSUE THREAD

**Issue by mxtsdev** [CKingX/ddrescue_error_mapping#2]
Hello,

I'm getting the error `Unable to mount image` when I try to use the tool to mount a 128GB image and map file created by HDDSuperClone. I found the problem appears to be with the call to dmsetup which returns the following error:
```
Unable to mount image Os { code: 7, kind: ArgumentListTooLong, message: "Argument list too long" }
```

I'm unsure if multiple lines are supported using the --table switch but for large map files using standard input to write the table to dmsetup is probably a must.

Thank you for your work on this tool!

**Comment by CKingX** [comment]
I am looking into using stdin now.

**Comment by CKingX** [comment]
Could you check if it is fixed in [v1.0.0 beta 2](https://github.com/CKingX/ddrescue_error_mapping/releases/tag/v1.0.0-beta.2)?

**Comment by CKingX** [comment]
Also is it possible to attach the ddrescue log file? I would like to add it to the tests I run

**Comment by mxtsdev** [comment]
Got the same error on the first run, so I removed the --table arguments from mount.rs and recompiled.

Second run:
```
device-mapper: reload ioctl on ddrm0 failed: Invalid argument
Command failed.
~/sdcard/project1.bin is mounted at /dev/mapper/ddrm0
```
Here is the log file:
https://pastebin.com/Rjxxyv04

I can look at it more closely later on tomorrow.

**Comment by CKingX** [comment]
I forgot to remove both --table and the parse argument being sent 🤦‍♂️. Now it should be fixed.

**Comment by mxtsdev** [comment]
The last error was due to something I did during testing. I edited the ddrescue log file and removed everything except the list of data blocks and then kept using the edited file when calling ddrescue_error_mapping.

The parse_map function always skips the first line (supposed to be the status line) regardless of content so the first device mapping entry ( `0 15786240 linear /dev/loop1 0`) did not get generated was missing from the device mapping which causes the error from the second run.

**Comment by CKingX** [comment]
Yeah I have it skip the first line that is not empty or has a comment for that reason. You are pretty familiar with ddrescue map files too😀

**Comment by mxtsdev** [comment]
Yes, the current version worked with the map file and I was able to read from the mounted device using DMDE.

The file that failed for me wasn't a valid ddrescue map file so not a problem with the parsing in ddrescue_error_map :)

**Comment by CKingX** [comment]
Ok thank you for confirming!
